# Generated by Django 5.0.6 on 2024-07-02 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_verifycodemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='verifycodemodel',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.usermodel'),
            preserve_default=False,
        ),
    ]
